liberror: new functions for checking and reporting errors
2 new functions were added. One checks the error against the list of
known errors, and the other provides a way of "printing" the errors.