liberror: use declare to determine function
Use declare -lF to determine if a function is defined or not, rather
than the less effective (and less elegant) tricks with type. This is
likely a bashism though.