liberror: clarify checkerror() description header
Clarify the description header for checkerror() so that it both more
accurately describes the function and gives more detail as to how to use
the function.