liberror: don't unconditionally rely on libcolor
Don't force usage of libcolor (using the variables is fine because if
libcolor isn't loaded they won't harm anything). Also fixed a few typos.