liberror: function for errorcode creation/handling
There is now a function for adding new error codes with corresponding
messages. This eases the burden of maintaining lists of error codes, as
developers no longer need to track error code numbers directly, and also
coalesces a code and its message into a single line rather than the
developer having to maintain them separately. This also has the result
of cleaner and smaller code.

The original method of directly modifying the error code values and
error message array can still be used when low-level error code access
is required, but the new method (via liberror_add_error) is now the
preferred method for defining error codes and messages. All defined
errors in both the cauldron and enchantment components have been
converted to this new method. Ward has also accordingly been updated to
handle testing the error codes via the new method.