liberror: implement printerror()
Previously printerror() was implemented with "place-holder" code. The
code has now been fleshed out, where the error message is actually
filled in instead of printing a null variable. Also, it isn't hardcoded
for only cauldron errors, but can now also handle enchant errors.