liberror: improve check functions
Improve the check functions by having them immediately return an "OK" result if
the incoming error code matches that of ERR_OK. Also have them test against
ERR_OK instead of hardcoding the OK value as 0.