liberror: add context variable
liberror is used by both cauldron as well as enchant, so knowing which
context liberror is being accessed from is useful (separation of
error codes, error messages, etc.). This variable can be set in the
caller, but defaults to cauldron (enchant *must* set this).